/*
 * Filip´s API of Things
 * Some description here of the full API  GitHub Flavored Markdown can be used for rich text representation,     such as **bold**, *italic* and [links](https://swagger.io).           # Useful links for the tasks:  * **[REST Design Guidelines V4](https://confluence.tech.dnb.no/pages/viewpage.action?pageId=33488367)**  * **[SwaggerHub Way of Work](https://confluence.tech.dnb.no/display/KKO/SwaggerHub%3A+REST+API+Design+tool\\#SwaggerHub:RESTAPIDesigntool-WayofWork)**      
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ThingBase;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.LocalDate;

/**
 * Thing is inherited from ThingBase and adds several new fields. Required fields are those that are always set when object is returned to the client 
 */
@ApiModel(description = "Thing is inherited from ThingBase and adds several new fields. Required fields are those that are always set when object is returned to the client ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-04-14T11:51:05.361Z")



public class Thing extends ThingBase {
  @SerializedName("thingId")
  private String thingId = null;

  @SerializedName("field5")
  private LocalDate field5 = null;

  public Thing thingId(String thingId) {
    this.thingId = thingId;
    return this;
  }

   /**
   * Thing identifier
   * @return thingId
  **/
  @ApiModelProperty(value = "Thing identifier")
  public String getThingId() {
    return thingId;
  }

  public void setThingId(String thingId) {
    this.thingId = thingId;
  }

  public Thing field5(LocalDate field5) {
    this.field5 = field5;
    return this;
  }

   /**
   * Description goes HERE
   * @return field5
  **/
  @ApiModelProperty(example = "1999-04-15", value = "Description goes HERE")
  public LocalDate getField5() {
    return field5;
  }

  public void setField5(LocalDate field5) {
    this.field5 = field5;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Thing thing = (Thing) o;
    return Objects.equals(this.thingId, thing.thingId) &&
        Objects.equals(this.field5, thing.field5) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(thingId, field5, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Thing {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    thingId: ").append(toIndentedString(thingId)).append("\n");
    sb.append("    field5: ").append(toIndentedString(field5)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

