/**
 * Filip´s API of Things - forked
 * Some description here of the full API  GitHub Flavored Markdown can be used for rich text representation,     such as **bold**, *italic* and [links](https://swagger.io).           # Useful links for the tasks:  * **[REST Design Guidelines V4](https://confluence.tech.dnb.no/pages/viewpage.action?pageId=33488367)**  * **[SwaggerHub Way of Work](https://confluence.tech.dnb.no/display/KKO/SwaggerHub%3A+REST+API+Design+tool\\#SwaggerHub:RESTAPIDesigntool-WayofWork)**      
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ErrorResponse (
  /* Error code (determined on this API service): Any Errorcode important enough to need handling by consumer should be promotoed to a specific status code value and shown in this field.  */
  statusCode: String,
  /* Readable message associated with statuscode. */
  message: String,
  /* Error responses from backend systems. This data is optional and can not be considered as always present. Any errors that need custom handling should be promotoed to the required statusCode field  */
  backendInfo: Option[Seq[BackendResponse]] = None
) extends ApiModel


