/**
 * Petter's forked version of Filip´s API of Things
 * Some description here of the full API  GitHub Flavored Markdown can be used for rich text representation,     such as **bold**, *italic* and [links](https://swagger.io).           # Useful links for the tasks:  * **[REST Design Guidelines V4](https://confluence.tech.dnb.no/pages/viewpage.action?pageId=33488367)**  * **[SwaggerHub Way of Work](https://confluence.tech.dnb.no/display/KKO/SwaggerHub%3A+REST+API+Design+tool\\#SwaggerHub:RESTAPIDesigntool-WayofWork)**      
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Thing (
  /* Description of field goes HERE */
  field1: Option[String] = None,
  /* Description of field goes HERE */
  field2: Option[Int] = None,
  /* Description of field goes HERE */
  field3: Option[Double] = None,
  /* Description of field goes HERE */
  field4: Option[ThingEnums.Field4] = None,
  /* Thing identifier */
  thingId: Option[String] = None,
  /* Description goes HERE */
  field5: Option[Date] = None
) extends ApiModel

object ThingEnums {

  type Field4 = Field4.Value
  object Field4 extends Enumeration {
    val VAL1 = Value("VAL1")
    val VAL2 = Value("VAL2")
    val VAL3 = Value("VAL3")
  }

}

